name: learn_english
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartz: ^0.10.0
  dio: ^4.0.0
  flutter_mobx: ^2.0.2
  mobx: ^2.0.4
  flutter_modular: ^3.4.1+1
  web_scraper: ^0.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.15
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
  mobx: flutter pub get & flutter pub run build_runner watch
  mobxc: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs
